### ISSUE TITLE
Enabling CONFIG_NETWORK_PHY_TIMESTAMPING

### ISSUE THREAD

**Issue by greyghost509** [Sabayon/kernel#4]
Duplicating from https://bugs.sabayon.org/show_bug.cgi?id=5866:

This kernel option might be enabled by default to allow PTP time synchronization (IEEE 1588-2008) to work. There are no big drawbacks to be expected from turning this on by default, Ubuntu made this change, too:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1785816

**Comment by geaaru** [comment]
thanks, for your issue, I will enable it on branch 5.4 and 5.5 in the next days. After my fix, the new release will be available with this option.

**Comment by greyghost509** [comment]
Am Fri, 10 Jan 2020 06:48:24 -0800
schrieb geaaru <notifications@github.com>:

> thanks, for your issue, I will enable it on branch 5.4 and 5.5 in the
> next days. After my fix, the new release will be available with this
> option.

Great, thanks!

**Comment by geaaru** [comment]
PR https://github.com/Sabayon/kernel/pull/5 fix this.

**Comment by geaaru** [comment]
Done. The next 5.4 tag will contain CONFIG_NETWORK_PHY_TIMESTAMPING. ;)

**Comment by greyghost509** [comment]
Am Tue, 28 Jan 2020 04:25:24 -0800
schrieb geaaru <notifications@github.com>:

> Done. The next 5.4 tag will contain CONFIG_NETWORK_PHY_TIMESTAMPING. ;)

Thanks a lot!


cu
  gg
